theme="robust"
BaseURL: "http://example.com"
LanguageCode: "zh-CN"
Title: "Robust"
paginate = 10 # optional
copyright = "Copyright (c) 2015 - 2016, Your Name; all rights reserved."
watch = true # optional
uglyurls = false # optional 使用.html后缀

Params:
  Author: "Your name."
  Birth: "Sun, Feb 26, 1989"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "Your ID."
  GravatarHash: "Your Hash."
  SyntaxHighlightTheme: "solarized_dark.min.css"
  ShowRelatedPost: True
  ShowTagCloud: True
  
  AuthorDes: "博主介绍"
  Profile: "images/profile.jpg" # 博主头像
  Logo: "images/logo.jpg" # 头部图片
  UyanId: "1234567" # 友言id
  comment: true # 开启评论
  uglyurls: False # 使用.html后缀
  
Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:title/ #开启这个后uglyurls参数对文章无效。

MetadataFormat: "yaml"

